Added CppAD to ThirdParty and updated the build system. It is no longer necessary to provide the --with-cppad flag, although this option is still supported.
git-svn-id: https://svn.jmodelica.org@561 7ae51c65-13d5-4921-9d80-6511ddd1419c

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -19602,19 +19602,6 @@ else
 fi
 
 
-
-
-#AS_IF([test "x$with_ipopt" = xno],
-#      [AC_MSG_FAILURE([--with-ipopt not specified])],
-#       [AC_MSG_RESULT([ ])
-#       AC_MSG_RESULT([***********************************************************************])
-#       AC_MSG_RESULT([* --with-ipopt option specified - compiling with IPOPT support        *])
-#       AC_MSG_RESULT([***********************************************************************])
-#       AC_MSG_RESULT([ ])
-#       AC_CHECK_FILE($ipopt/include/coin/IpStdCInterface.h,
-#                     [],
-#                     [AC_MSG_FAILURE([--with-ipopt option was specified but does not seem to point at a valid IPOPT installation])])])
-
 # Set output variables to be exported to the Makefiles
 
 
@@ -19642,28 +19629,42 @@ fi
 
 
 if test "x$with_cppad" = xno; then
-  { echo "$as_me:$LINENO: result:  " >&5
-echo "${ECHO_T} " >&6; }
-       { echo "$as_me:$LINENO: result: ***********************************************************************" >&5
-echo "${ECHO_T}***********************************************************************" >&6; }
-       { echo "$as_me:$LINENO: result: * --with-cppad option not specified - compiling without CppAD support *" >&5
-echo "${ECHO_T}* --with-cppad option not specified - compiling without CppAD support *" >&6; }
-       { echo "$as_me:$LINENO: result: ***********************************************************************" >&5
-echo "${ECHO_T}***********************************************************************" >&6; }
-       { echo "$as_me:$LINENO: result:  " >&5
-echo "${ECHO_T} " >&6; }
+  cppad="ThirdParty/CppAD/cppad-20090303.0/"
+fi
+
+
+if test "x$with_cppad" = xno; then
+  as_ac_File=`echo "ac_cv_file_$srcdir/$cppad/cppad/cppad.hpp" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $srcdir/$cppad/cppad/cppad.hpp" >&5
+echo $ECHO_N "checking for $srcdir/$cppad/cppad/cppad.hpp... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  { echo "$as_me:$LINENO: result:  " >&5
-echo "${ECHO_T} " >&6; }
-       { echo "$as_me:$LINENO: result: ***********************************************************************" >&5
-echo "${ECHO_T}***********************************************************************" >&6; }
-       { echo "$as_me:$LINENO: result: * --with-cppad option specified - compiling with CppAD support        *" >&5
-echo "${ECHO_T}* --with-cppad option specified - compiling with CppAD support        *" >&6; }
-       { echo "$as_me:$LINENO: result: ***********************************************************************" >&5
-echo "${ECHO_T}***********************************************************************" >&6; }
-       { echo "$as_me:$LINENO: result:  " >&5
-echo "${ECHO_T} " >&6; }
-       as_ac_File=`echo "ac_cv_file_$cppad/cppad/cppad.hpp" | $as_tr_sh`
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$srcdir/$cppad/cppad/cppad.hpp"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: --with-cppad option was specified but does not seem to point at a valid CppAD installation
+See \`config.log' for more details." >&5
+echo "$as_me: error: --with-cppad option was specified but does not seem to point at a valid CppAD installation
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+else
+  as_ac_File=`echo "ac_cv_file_$cppad/cppad/cppad.hpp" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $cppad/cppad/cppad.hpp" >&5
 echo $ECHO_N "checking for $cppad/cppad/cppad.hpp... $ECHO_C" >&6; }
 if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -19695,6 +19696,11 @@ fi
 fi
 
 
+if test "x$with_cppad" = xno; then
+  with_cppad=automatic
+fi
+
+
  if test "x$with_cppad" != xno; then
   COMPILE_WITH_CPPAD_TRUE=
   COMPILE_WITH_CPPAD_FALSE='#'
@@ -19707,7 +19713,12 @@ fi
 # Set output variables to be exported to the Makefiles
 
 
-CPPAD_INC=$cppad
+if test "x$with_cppad" = xautomatic; then
+  CPPAD_INC=`cd $srcdir; pwd`/$cppad
+else
+  CPPAD_INC=$cppad
+fi
+
 
 if test "x$with_cppad" != xno; then
   WITH_CPPAD="true"
