Merge to stable (Up to r10192)
git-svn-id: https://svn.jmodelica.org@10194 7ae51c65-13d5-4921-9d80-6511ddd1419c

diff --git a/branches/stable/jm_tests.in b/branches/stable/jm_tests.in
--- a/branches/stable/jm_tests.in
+++ b/branches/stable/jm_tests.in
@@ -48,6 +48,14 @@ set -o pipefail
 
 PYTHONPATH="$(merge_path "${PYTHONPATH}" "${JMODELICA_HOME}/Python/")"
 
+# Default paths to ant files used for unit tests
+if [[ -z "MC_ANT_ARGS" ]]; then
+    MC_ANT_ARGS=${JMODELICA_SRC}/Compiler/ModelicaCompiler/build.xml
+fi
+if [[ -z "OC_ANT_ARGS" ]]; then
+    OC_ANT_ARGS=${JMODELICA_SRC}/Compiler/OptimicaCompiler/build.xml
+fi
+
 # Find operating system
 SYS="$(uname -s)"
 if [[ "${SYS}" == "Darwin" ]]; then
@@ -290,7 +298,11 @@ function nose_test() {
 }
 
 function ant_test() {
-  ant -f ${JMODELICA_SRC}/Compiler/$1Compiler/build.xml ${CLEAN_JUNIT} test
+  if [[ "$1" == "Modelica" ]]; then
+    ant -f ${MC_ANT_ARGS} ${CLEAN_JUNIT} clean-test test
+  else
+    ant -f ${OC_ANT_ARGS} ${CLEAN_JUNIT} clean-test test
+  fi
 }
 
 function build_jmodelica() {
@@ -399,7 +411,7 @@ function read_args() {
             ARG_TYPE=xmlResPath
             ;;
           e)
-            RETURN_WITH_ERROR=1
+            ERROR_ON_TEST_FAIL=1
             ;;
           h)
             echo "usage: tests [-ajmopvnqcCh] { [-(t|g) [tag1 ...]] } [-f file1 ...] [-x path]"
@@ -432,8 +444,9 @@ function read_args() {
             echo "      contains the results of the tests. Currently doesn't handle spaces"
             echo "      in the supplied path!"
             echo "  -e  When enabled, exit with error code (after running all "
-            echo "      tests) if any test suite return with an error code (won't trigger on "
+            echo "      tests) if any test suite return with an error code or a test fails"
             echo "      regular failures or errors). Default behaviour is exit 0.".
+            echo "      Requires -x".
             echo "  -h  Print this help and exit"
             exit
             ;;
@@ -460,6 +473,13 @@ export JAVA_HOME JMODELICA_HOME IPOPT_HOME PYTHONPATH LD_LIBRARY_PATH ANT_OPTS S
 TIME=$(date +%s)
 
 read_args "$@"
+
+if [[ $ERROR_ON_TEST_FAIL == 1 ]]; then
+    if [[ -z $XML_RES_PATH ]]; then
+        echo "-e needs -x"
+        exit 1
+    fi
+fi
 
 if [ "${LOG}" == 1 ]; then
   echo "Log of jm_tests $(date):" > "${LOGFILE}"
@@ -492,7 +512,11 @@ if [[ "${OUTPUT}" != q ]]; then
 fi
 echo $(date +%s) ${TIME}"-[Total time: ]nd60/n[:]n60%[0n]sxd10>xp" | dc
 
-if [ "${RETURN_WITH_ERROR}" == 1 ]; then
+if [[ "${ERROR_ON_TEST_FAIL}" == 1 ]]; then
+    if [[ $res == 0 ]]; then
+        grep -R testsuite $XML_RES_PATH | sed -n -e "/.*errors=\"[0]*[1-9][0-9]*\".*/ q1" -e "/.*failures=\"[0]*[1-9][0-9]*\".*/ q1"
+        exit $?
+    fi
     exit $res
 else
     exit 0
